name: SOCKS5 Proxy

on:
  schedule:
    - cron: '0 */10 * * *'
  workflow_dispatch:

jobs:
  proxy:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - name: Install Gost
        run: |
          wget -O gost.tar.gz https://github.com/ginuerzh/gost/releases/download/v2.11.5/gost-linux-amd64-2.11.5.gz
          gunzip gost.tar.gz
          chmod +x gost-linux-amd64-2.11.5
          sudo mv gost-linux-amd64-2.11.5 /usr/local/bin/gost

      - name: Run SOCKS5 Server
        run: gost -L=socks5://:8080

      - name: Run SOCKS5 Server
        shell: bash
        run: chisel server --socks5 --port 8080 --reverse
